### ISSUE TITLE
As a signed in user I want to be able to launch the game with my account

### ISSUE THREAD

**Issue by ascense** [ascense/eternalreckoning#17]
- [ ] **Subscription** Create login session for user #18 
- [ ] **Subscription** Broadcast login session data #19 
- [ ] **Lobby** Receive session token from subscription service #20 
- [ ] **Lobby** Send authentication response with session token to launcher #21 
- [ ] **Launcher** Receive authentication response with session token from lobby server #22 
- [ ] **Launcher** Launch client with session token #23 
- [ ] **Client** Allow launching with session token #24
