### ISSUE TITLE
As a user I want to sign in to my account, so that I can retain my data across multiple sessions

### ISSUE THREAD

**Issue by ascense** [ascense/eternalreckoning#7]
- [ ] **Launcher** Username and password inputs #8 
- [ ] **Launcher** Send authentication request to lobby server #9
- [ ] **Lobby** Handle authentication requests from launcher #10
- [ ] **Lobby** Send authentication request to subscription service #11
- [ ] **Subscription** Handle authentication requests #12
- [ ] **Subscription** Verify user credentials #13
- [ ] **Lobby** Receive authentication response from subscription service #14
- [ ] **Lobby** Send authentication response to launcher #15
- [ ] **Launcher** Receive authentication response from lobby server #16
